name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Lint Kontrolü
        run: npm run lint

      - name: Testleri Çalıştır
        run: npm test
   